#!/bin/bash

echo "pre-push: Running a build to ensure documentation and bundle is up-to-date"

npm run doc

if git ls-files -m API.md | grep .
then
    echo "pre-push: Error - uncommited documentation changes to API.md; please commit those before pushing"
    exit 1
fi
